# Generated by Django 3.1.7 on 2021-03-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='discription',
            new_name='description',
        ),
    ]
